### ISSUE TITLE
Roadmap de Features

### ISSUE THREAD

**Issue by fdemian** [UTNianos/frontend#39]
Antes de sacar la primera versión necesitamos tener un roadmap de features. De ahi tenemos que ver a que le apuntamos para una primera release. 

Abro este issue para que nos pongamos a discutir que features apuntamos para la release V1.

**Comment by gndelia** [comment]
diria login/authenticacion y pulir  un poco mas el seguidor
con eso yo ya lo sacaria. Asi la gente empieza a poder jugar un poco con el seguidor y eso, y de paso avanzamos un poco. Capaz tambien asi podemos atraer algunos devs a colaborar

**Comment by fdemian** [comment]
Ok, me gustaría que se meta @Javier-Rotelli a ver si tiene alguna otra propuesta. Por ahora estaría bueno empezar a aglomerar las features esperadas acá, después abrimos un issue por feature y les podemos ir dando prioridad. 

Por ahora tenemos. 

- Tweaks al seguidor (que tipo de tweaks?). 
- Login
- Customizar el estado por cada user logueado / ver si se puede hacer el login.
- Guardar el estado de carrera en algún lado ? (no se si es factible debido a que no se el estado actual del backend).

**Comment by gndelia** [comment]
> Tweaks al seguidor (que tipo de tweaks?).

**Comment by gndelia** [comment]
darle un p

**Comment by gndelia** [comment]
> Tweaks al seguidor (que tipo de tweaks?).
darle un poco de amor a la UX en general.

**Comment by fdemian** [comment]
Ok, tenes algun ejemplo concreto que podamos meter en una task encarando al futuro inmediato?

**Comment by gndelia** [comment]
No es para arreglar, sino que podríamos ir creando issues y viendo

- [ ] la vistas mobile parece estar rota
![image](https://user-images.githubusercontent.com/352474/57993820-f4a76080-7a90-11e9-8411-8fdb0fcd693a.png)

- [ ] los colores: es todo blanco ! habria q ver si conseguimos un diseñador (lastima que hale desaparecio, a el le copaba lo de UX, habria q recontactarlo) y tener un esquemita de colores.

si no yo le puedo tirar la onda a alguno del laburo pero dudo que lo haga gratis (puedo averiguar, though)

- [ ] El código de la NavBar es medio un lio, hay cosas repetidas y hay partes que mepa que no se usan o no estoy viendo como hacer que aparezcan en la aplicacion (Ej el componente del avatar)

- [ ] conseguir los datos de las carreras; por ahora son un json harcodeado. Estaría bueno que el backend pueda devolver eso.


- [ ] el state parece estar roto. Hay una variable "isLoggedIn" o no, y cuando la paso a true (mientras pruebo lo de autenticacion con auth0) se me rompe toda la app: Intenta leer estados sobre session, notificaciones, y otras cosas que no están en la store. Falta codigo?

**Comment by fdemian** [comment]
Ok, eso suena como algo mas concreto. La navbar la copie de otro proyecto mío y la verdad es que el código mejoro leguas desde ese entonces, tengo que ver de traspasar los fixes y hacer cleanup más extensivo. 

Puede que falte código con el tema del state, no esta pensado de manera genial tampoco, en el medio tenemos reducers/selector/etc, y puede terminar siendo una mezcolanza todo.

Respecto a los colores de la UI, cuando tengamos sugerencias concretas, da para charlarlo. Por ahora lo dejaría como esta.

**Comment by gndelia** [comment]
ejemplo 

https://github.com/UTNianos/frontend/search?q=session&unscoped_q=session   

session no está salvo en ese lugar definido en todo el proy. Supongo que debe haber colgado.
Igual no te preocupes por eso

lo que hay que definir es el tema auth0

el problema mas q nada hoy es que los ads no nos permiten participar del programa OSS (no hay drama con las donaciones)

y la vdd es bastante caro auth0. Si bien podemos usarlo para pruebas no se si es sostenible en el tiempo

**Comment by fdemian** [comment]
Da para otra conversación esto. Yo diría que si tenemos espacio en el server, un servidor que implemente oauth conectado con el backend de UTNianos es más barato. No es más sencillo, ni es trivial de hacer.

Por lo que veo auth0 tiene el plan mas barato a U$S13 por mes (1000 users activos) y el más caro a U$S743 por mes (5000 usuarios y 100 "corporativos"). Es un salto gigante.
